name: Android CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: 'gradle'

    - name: Decode or Generate Debug Keystore
      run: |
        if [ -f "debug.keystore.base64" ]; then
          echo "Decoding debug.keystore.base64..."
          base64 -d debug.keystore.base64 > debug.keystore
        else
          echo "Generating a debug.keystore using keytool..."
          keytool -genkey -v -keystore debug.keystore -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US"
        fi

    - name: Grant Execute Permission to Gradlew
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease --stacktrace

    - name: Find and Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/*.apk
        if-no-files-found: error
